language: go

go:
  - 1.13.x
  - tip

before_install:
  - go get github.com/mattn/goveralls

script:
  - go test -v -gcflags=-l ./... -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - goveralls -v -service travis-ci -coverprofile=coverage.txt

