// Code generated by embed. DO NOT EDIT.

package templates

import (
	"github.com/inabyte/embed/embedded"
	"unsafe"
)

// FS return file system
var FS embedded.FileSystem

var templatesData [10022]byte

func init() {

	bytes := templatesData[:]
	str := *(*string)(unsafe.Pointer(&bytes))

	FS = embedded.New(5)

	FS.AddFile( /* /fs.go */ str[10016:10022],
		/* fs.go */ str[10017:10022],
		"",
		13033, 1581811583,
		/* text/plain; charset=utf-8 */ str[9955:9980],
		/* i9RWy3eZ7n315koQ_hOgslduSLA-gz */ str[9895:9925],
		true, bytes[0:4037], str[0:4037])

	FS.AddFile( /* /fs_test.go */ str[9995:10006],
		/* fs_test.go */ str[9996:10006],
		"",
		13349, 1581810827,
		/* text/plain; charset=utf-8 */ str[9955:9980],
		/* veLuC0ey7xzGI4LKlepQrtVCvQs-gz */ str[9925:9955],
		true, bytes[4037:7061], str[4037:7061])

	FS.AddFile( /* /server.go */ str[10006:10016],
		/* server.go */ str[10007:10016],
		"",
		4705, 1581811858,
		/* text/plain; charset=utf-8 */ str[9955:9980],
		/* MBLxmmA4MTo2axIC2LVINsGnwCA-gz */ str[9835:9865],
		true, bytes[7061:8905], str[7061:8905])

	FS.AddFile( /* /server_test.go */ str[9980:9995],
		/* server_test.go */ str[9981:9995],
		"",
		2722, 1581810843,
		/* text/plain; charset=utf-8 */ str[9955:9980],
		/* ZeZNWLAVt5neOZqOvGmHPA2Yngk-gz */ str[9865:9895],
		true, bytes[8905:9835], str[8905:9835])

	FS.AddFolder( /* / */ str[9959:9960],
		/* / */ str[9959:9960],
		"",
		1581810752,
		/* /fs.go */ str[10016:10022],
		/* /fs_test.go */ str[9995:10006],
		/* /server.go */ str[10006:10016],
		/* /server_test.go */ str[9980:9995],
	)
}
