// Code generated by embed. DO NOT EDIT.

package templates

import (
	"crypto/sha1"
	"encoding/base64"
	"github.com/inabyte/embed/embedded"
	"testing"
)

func TestFileServer(t *testing.T) {
	if FileHandler() == nil {
		t.Errorf("Call to FileServer did no return a handler")
	}
}

func TestBytes(t *testing.T) {
	FS.Walk(func(path string, info embedded.FileInfo) error {
		if !info.IsDir() {
			if getTag(info.Bytes()) != info.Tag() {
				t.Errorf("checksum for file %s doesn't match recorded", path)
			}
		}
		return nil
	})
}

func TestString(t *testing.T) {
	FS.Walk(func(path string, info embedded.FileInfo) error {
		if !info.IsDir() {
			s := info.String()
			if getTag([]byte(s)) != info.Tag() {
				t.Errorf("checksum for file %s doesn't match recorded {%s}", path, s)
			}
		}
		return nil
	})
}

func getTag(data []byte) string {
	hash := sha1.Sum(data)
	return base64.RawURLEncoding.EncodeToString(hash[:]) + "-gz"
}
